name: indoor_floral_plants
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0



  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rainbow.jpg"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/pics/
  
  fonts:
    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf