name: Deploy

on:

  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name : Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name : Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'

      - name: Flutter Pub get
        run : |
          echo  flutter clean
          echo  flutter pub get

      - name : Flutter Analyze
        run  : flutter analyze



      - name: Build
          run: flutter build appbundle --flavor prod

          - uses: r0adkll/upload-google-play@v1
            with:
              serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_TEXT }}
              packageName: com.kendi.indoor_floral_plants
              releaseFile: build/app/outputs/bundle/prodRelease/app-prod-release.aab
              track: internal
